export const initialState = {
  isStart: true ,
  name: '',
  userTag : '',
  bio : '',
  photo : '',
  status : 'Student',
  nameDirty : true,
  hashDirty : true,
  languagesKnow : [],
  languagesLearn : [],
  courses:[],
  teachers : [],
  loginUser:[],
  registerUser: null,
  isAuth:false,
  currentCourse:null,
  currentChat:[],
  socket:null,
  chatStatus:"course",
  messagesWithStudent:[],
  onlineUsers:[],
  currentCourseChat:null,
  currentCourseTeacher:null,
  chatsWithTeacher:null,
  chatsWithStudents:null,
  interlocutor:null,
  chatWithMemberCourse:null,
  createCourseData:{
    title:"",
    language:"",
    level:"",
    duration:"",
    startDate:"",
    finishDate:"",
    description:"",
    topics:[]
  }
}