export const initialState = {
  isStart: true ,
  name: '',
  userTag : '',
  bio : '',
  photo : '',
  status : 'Student',
  nameDirty : true,
  hashDirty : true,
  languagesKnow : [],
  languagesLearn : [],
  courses:[],
  teachers : [],
  loginUser:null,
  registerUser: null,
  isAuth:true,
  currentCourse:null,
  currentChat:null,
  timeCurrentChat:null
}