export const initialState = {
  isStart: true ,
  name: '',
  userTag : '',
  bio : '',
  photo : '',
  status : 'Student',
  nameDirty : true,
  hashDirty : true,
  languagesKnow : [],
  languagesLearn : [],
  courses:[],
  loginUser:null,
  registerUser: null,
  isAuth:false,
  currentCourse:null,
}